create table warehouse_item_types (
    id bigserial primary key not null,
    version bigint,
    title varchar(255) not null,
    units varchar(10),
    gtin varchar(32),
    item_group varchar(255) not null,
    item_subgroup varchar(255)
);

insert into warehouse_item_types (version, title, units, gtin, item_group, item_subgroup) values 
('0','Японские благовония SHIN MAINICHIKOH', 'шт', null,'GOODS','GOODS_PURCHASED'),
('0','Японские благовония Mainichikoh Natural', 'шт', null,'GOODS','GOODS_PURCHASED'),
('0','Японские благовония Mainichikoh Natural Cherry blossoms', 'шт', null,'GOODS','GOODS_PURCHASED'),
('0','Японские благовония MAINICHIKOH Aqua', 'шт', null,'GOODS','GOODS_PURCHASED'),
('0','Японские благовония SEIUN GOLD', 'шт', null,'GOODS','GOODS_PURCHASED'),
('0','Японские благовония SEIUN Amore', 'шт', null,'GOODS','GOODS_PURCHASED'),
('0','"Гречишный чай "Яблоко с корицей"', 'кг', null,'GOODS','GOODS_PURCHASED'),
('0','Ромашка (головки)', 'кг', null,'GOODS','GOODS_PURCHASED'),
('0','Мелисса лист', 'кг', null,'GOODS','GOODS_PURCHASED'),
('0','Королевский шиповник', 'кг', null,'GOODS','GOODS_PURCHASED'),
('0','Венчик для чая Матча', 'шт', null,'GOODS','GOODS_PURCHASED'),
('0','Бай Хао Инь Чжень', 'кг', null,'GOODS','GOODS_PURCHASED'),
('0','Стул с деревянным каркасом', 'шт', null,'NON_CURRENT_ASSETS', 'NCA_PURCHASED'),
('0','Полка модель Y2409096720', 'шт', null,'NON_CURRENT_ASSETS', 'NCA_PURCHASED'),
('0','Ширма дерево', 'шт', null,'NON_CURRENT_ASSETS', 'NCA_PURCHASED'),
('0','Японские благовония JINKOH EIJU', 'шт', null,'GOODS','GOODS_PURCHASED'),
('0','Японские благовония KYARA EIJU', 'шт', null,'GOODS','GOODS_PURCHASED'),
('0','Японские благовония Shinsei Eiju', 'шт', null,'GOODS','GOODS_PURCHASED'),
('0','Фильтр-пакеты для заваривания S (маленькие)', 'шт', null,'GOODS','GOODS_PURCHASED'),
('0','"Зелёный чай "Шэн пуэр "Иу Гу Шу"', 'кг', null,'GOODS','GOODS_PURCHASED'),
('0','"Зелёный чай "Шэн пуэр "Зеленый Иероглиф"', 'кг', null,'GOODS','GOODS_PURCHASED'),
('0','"Зелёный чай "Шэн пуэр "Чантай"', 'кг', null,'GOODS','GOODS_PURCHASED'),
('0','"Зелёный чай "ГАБА Хэй Хо "', 'кг', null,'GOODS','GOODS_PURCHASED'),
('0','"Зелёный чай "ГАБА Ruby Sour "', 'кг', null,'GOODS','GOODS_PURCHASED'),
('0','"Зелёный чай "ГАБА "Аметист"', 'кг', null,'GOODS','GOODS_PURCHASED'),
('0','"Зелёный чай "Те Гуань Инь "Old School"', 'кг', null,'GOODS','GOODS_PURCHASED'),
('0','"Зелёный чай "Те Гуань Инь Гуо Сян"', 'кг', null,'GOODS','GOODS_PURCHASED'),
('0','"Зелёный чай "Те Гуань Инь Гуо Сян Мао Ча"', 'кг', null,'GOODS','GOODS_PURCHASED'),
('0','"Чёрный чай "Шуй Сянь"', 'кг', null,'GOODS','GOODS_PURCHASED'),
('0','"Чёрный чай "Да Хун Пао"', 'кг', null,'GOODS','GOODS_PURCHASED');
